// Generated by Haxe 4.0.2
(function ($global) { "use strict";
var HxOverrides = function() { };
HxOverrides.substr = function(s,pos,len) {
	if(len == null) {
		len = s.length;
	} else if(len < 0) {
		if(pos == 0) {
			len = s.length + len;
		} else {
			return "";
		}
	}
	return s.substr(pos,len);
};
var rmzrkr_app_MetalCamp2020App = function() {
	this.version = "0.3";
	console.log("src/rmzrkr/app/MetalCamp2020App.hx:16:","Iniciando MetalCamp2020App v" + this.version);
	var seccion = window.location.hash.length > 0 ? HxOverrides.substr(window.location.hash,1,null) : "inicio";
	this.goToRoute(seccion);
};
rmzrkr_app_MetalCamp2020App.main = function() {
	var els = window.document.getElementsByTagName("section");
	var _g = 0;
	while(_g < els.length) {
		var seccion = els[_g];
		++_g;
		rmzrkr_app_MetalCamp2020App.secciones.push(seccion.id);
	}
	console.log("src/rmzrkr/app/MetalCamp2020App.hx:41:",rmzrkr_app_MetalCamp2020App.secciones);
	rmzrkr_app_MetalCamp2020App.app = new rmzrkr_app_MetalCamp2020App();
};
rmzrkr_app_MetalCamp2020App.prototype = {
	goToRoute: function(seccion) {
		var _g = [];
		var _g1 = 0;
		var _g2 = rmzrkr_app_MetalCamp2020App.secciones;
		while(_g1 < _g2.length) {
			var v = _g2[_g1];
			++_g1;
			if(v == seccion) {
				_g.push(v);
			}
		}
		var filtrado = _g;
		seccion = filtrado.length > 0 ? seccion : "inicio";
		window.location.replace("#" + seccion);
	}
};
rmzrkr_app_MetalCamp2020App.secciones = [];
rmzrkr_app_MetalCamp2020App.main();
})({});
